// Code generated by MockGen. DO NOT EDIT.
// Source: node_visitor.go

// Package mock_agent is a generated GoMock package.
package mock_agent

import (
	types "chasqi-go/types"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockNodeVisitor is a mock of NodeVisitor interface.
type MockNodeVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockNodeVisitorMockRecorder
}

// MockNodeVisitorMockRecorder is the mock recorder for MockNodeVisitor.
type MockNodeVisitorMockRecorder struct {
	mock *MockNodeVisitor
}

// NewMockNodeVisitor creates a new mock instance.
func NewMockNodeVisitor(ctrl *gomock.Controller) *MockNodeVisitor {
	mock := &MockNodeVisitor{ctrl: ctrl}
	mock.recorder = &MockNodeVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeVisitor) EXPECT() *MockNodeVisitorMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockNodeVisitor) Delete(host, url string, headers, body map[string][]string) (*types.ResponseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", host, url, headers, body)
	ret0, _ := ret[0].(*types.ResponseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockNodeVisitorMockRecorder) Delete(host, url, headers, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockNodeVisitor)(nil).Delete), host, url, headers, body)
}

// Get mocks base method.
func (m *MockNodeVisitor) Get(host, url string, headers map[string][]string) (*types.ResponseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", host, url, headers)
	ret0, _ := ret[0].(*types.ResponseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockNodeVisitorMockRecorder) Get(host, url, headers interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockNodeVisitor)(nil).Get), host, url, headers)
}

// Post mocks base method.
func (m *MockNodeVisitor) Post(host, url string, headers, body map[string][]string) (*types.ResponseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", host, url, headers, body)
	ret0, _ := ret[0].(*types.ResponseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockNodeVisitorMockRecorder) Post(host, url, headers, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockNodeVisitor)(nil).Post), host, url, headers, body)
}

// Put mocks base method.
func (m *MockNodeVisitor) Put(host, url string, headers, body map[string][]string) (*types.ResponseResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", host, url, headers, body)
	ret0, _ := ret[0].(*types.ResponseResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockNodeVisitorMockRecorder) Put(host, url, headers, body interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockNodeVisitor)(nil).Put), host, url, headers, body)
}
